const fs = require('fs');
const path = require('path');

const langs = ['es', 'en', 'fr', 'pt'];
const dir = path.join(__dirname, 'src', 'translations');

const newKeys = {
  es: `    // Classes Landing (Clases.jsx)
    "clases.hero.title": "Crea, aprende, y disfruta cada mes.",
    "clases.hero.desc": "Cada mes descubrirás proyectos creativos, ideas e inspiración para disfrutar de la creatividad a tu ritmo y dedicarte un momento solo para ti.",
    "clases.hero.cta.unauth": "Quiero unirme al club",
    "clases.hero.cta.authSub": "Ir a mi Academia →",
    "clases.hero.cta.subtext": "Empieza hoy tu momento creativo.",
    "clases.hero.loginText": "¿Ya formas parte del club?",
    "clases.hero.loginLink": "Inicia sesión",

    "clases.whatIs.title": "¿Qué es el Club Creativo?",
    "clases.whatIs.p1": "El Club Creativo MERAKI es un espacio pensado para las personas que disfrutan creando con las manos, aprendiendo cosas nuevas y dedicándose un momento para desconectar del ritmo del día a día.",
    "clases.whatIs.p2": "Al suscribirte al club, formarás parte de una comunidad creativa donde cada mes encontrarás proyectos exclusivos, ideas inspiradoras y propuestas de manualidades que te ayudarán a seguir desarrollando tu creatividad de una forma sencilla y agradable.",
    "clases.whatIs.p3": "El objetivo del Club Creativo es acompañarte en tu camino creativo, ofreciéndote inspiración, aprendizaje y momentos de calma a través de las manualidades. No importa si estás empezando o si ya tienes experiencia: lo importante es tener ganas de crear y disfrutar del proceso.",
    "clases.whatIs.quote": "Más que un simple contenido, el Club Creativo es un lugar para dedicarte tiempo a ti misma, experimentar con nuevas técnicas y volver a conectar con el placer de crear.",

    "clases.benefits.title": "Beneficios de pertenecer al Club Creativo MERAKI",
    "clases.benefits.subtitle": "Si te gusta crear con tus manos, ahora también puedes hacerlo desde casa con nuestro Club Creativo MERAKI",
    "clases.benefits.b1.title": "Proyectos exclusivos cada mes",
    "clases.benefits.b1.desc": "Accede a propuestas creativas diseñadas especialmente para los miembros del club, con ideas nuevas para seguir disfrutando de las manualidades.",
    "clases.benefits.b2.title": "Inspiración constante",
    "clases.benefits.b2.desc": "Descubre nuevas técnicas, combinaciones y propuestas que te ayudarán a ampliar tus conocimientos y mantener viva tu creatividad.",
    "clases.benefits.b3.title": "Explicaciones claras y accesibles",
    "clases.benefits.b3.desc": "Los proyectos están pensados para que puedas realizarlos fácilmente, tanto si estás empezando como si ya tienes experiencia.",
    "clases.benefits.b4.title": "Tiempo para ti",
    "clases.benefits.b4.desc": "La creatividad es también una forma de relajarse y desconectar. El club te invita a dedicarte un momento de calma mientras creas con tus manos.",
    "clases.benefits.b5.title": "Ventajas especiales para miembros",
    "clases.benefits.b5.desc": "Los miembros del club podrán disfrutar de beneficios especiales relacionados con algunas actividades, talleres o propuestas de Meraki ArteSano.",
    "clases.benefits.b6.title": "Formar parte de una comunidad",
    "clases.benefits.b6.desc": "Un espacio donde compartir la pasión por las manualidades, aprender juntos y disfrutar del proceso creativo.",

    "clases.isForYou.title": "Este club es para ti si...",
    "clases.isForYou.subtitle": "El Club Creativo MERAKI está pensado para todas las personas que sienten que crear con las manos es una forma de disfrutar, relajarse y expresarse.",
    "clases.isForYou.li1": "Te gustan las manualidades y quieres seguir aprendiendo nuevas ideas y técnicas.",
    "clases.isForYou.li2": "Disfrutas creando y te gustaría dedicar más tiempo a tu creatividad.",
    "clases.isForYou.li3": "Buscas una actividad que te ayude a relajarte y desconectar del día a día.",
    "clases.isForYou.li4": "Te encanta descubrir proyectos nuevos y dejar volar tu imaginación.",
    "clases.isForYou.li5": "Quieres formar parte de un espacio creativo donde inspirarte.",
    "clases.isForYou.li6": "Si no puedes venir a las clases presenciales o prefieres crear a tu ritmo, el Club Creativo MERAKI está pensado para ti.",
    "clases.isForYou.bottomText": "No importa si estás empezando o si ya tienes experiencia: lo importante es tener ganas de crear y disfrutar del proceso.",

    "clases.pricing.title": "¿Qué incluye cada mes?",
    "clases.pricing.badge": "Club Creativo MERAKI",
    "clases.pricing.inc1": "Kit completo con todos los materiales.",
    "clases.pricing.inc1.sub": "Es muy importante para nosotros que lo que recibas sea de las mejores lanas españolas.",
    "clases.pricing.inc2": "Instrucciones impresas claras paso a paso.",
    "clases.pricing.inc3": "Acceso a 2h en directo a través de zoom o similar.",
    "clases.pricing.inc4": "Acceso a grabación.",
    "clases.pricing.inc5": "Grupo privado de Telegram.",
    "clases.pricing.inc6": "Proyecto exclusivo (dirigido tanto a crochet como a tricot).",
    "clases.pricing.inc7": "Entre todo lo que incluye cada mes, se incluirá alguna sorpresa!",
    
    "clases.pricing.cal.title": "📅 Calendario Mensual",
    "clases.pricing.cal.li1": "Del 21 al 30 → Preparacion de kits.",
    "clases.pricing.cal.li2": "Del 1 al 5 → Envío de cajas.",
    "clases.pricing.cal.li3": "Día 15 → Directo mensual 2h.",
    "clases.pricing.cal.li4": "Del 16 al 30 → Grabación disponible.",
    
    "clases.pricing.diff.title": "🌟 Nuestra Diferencia",
    "clases.pricing.diff.li1": "• Acompañamiento real en cada proyecto.",
    "clases.pricing.diff.li2": "• Resolverás tus dudas conmigo paso a paso.",
    "clases.pricing.diff.li3": "• Formarás parte de una comunidad que disfruta creando.",
    "clases.pricing.diff.li4": "• Recibirás todo en casa, listo para empezar.",
    "clases.pricing.diff.li5": "• Ventajas exclusivas en tienda y próximos kits.",

    "clases.card.badge": "🚀 OFERTA DE LANZAMIENTO",
    "clases.card.title": "Suscripción Mensual",
    "clases.card.officialPrice": "PRECIO OFICIAL 39€",
    "clases.card.price": "32",
    "clases.card.currency": "€/mes",
    "clases.card.founderBadge": "🔥 PRECIO FUNDADORAS el primer mes",
    "clases.card.limited": "Limitado a {max} plazas",
    "clases.card.spotsLeft": "solo quedan {left}",
    "clases.card.soldOut": "🔒 Plazas Agotadas",
    "clases.card.quote": '💡 "Un pequeño precio para grandes momentos creativos."',
    "clases.card.noCommitment": "Sin permanencia • Cancela cuando quieras",
    "clases.card.memberBtn": "✅ Ya soy miembro — Ir a mi Academia",
    "clases.card.joinBtn": "Quiero unirme al club",

    "clases.faq.title": "Preguntas Frecuentes (FAQ)",
    "clases.faq.q1": "¿Qué nivel de experiencia necesito?",
    "clases.faq.a1": "No necesitas experiencia previa. Cada proyecto sorpresa viene con guía paso a paso, fotos y consejos, para que puedas disfrutar creando desde el primer día.",
    "clases.faq.q2": "¿Qué incluye exactamente el kit?",
    "clases.faq.a2": "Cada mes recibirás todos los materiales necesarios para el proyecto sorpresa, más la guía de instrucciones. Solo necesitas tus ganas de crear.",
    "clases.faq.q3": "¿Puedo cancelar la suscripción en cualquier momento?",
    "clases.faq.a3": "Sí. La suscripción es mensual y flexible, puedes cancelarla en cualquier momento antes de que se envíe el siguiente kit.",
    "clases.faq.q4": "¿Qué pasa si no me gustan los colores o materiales?",
    "clases.faq.a4": "Seleccionamos materiales de calidad y colores combinables para todos los gustos. Cada kit está diseñado para que sea versátil y divertido.",
    "clases.faq.q5": "¿Cuándo recibo mi proyecto sorpresa?",
    "clases.faq.a5": "Los kits se envían al inicio de cada mes (día 7), para que puedas disfrutar de tu proyecto sorpresa lo antes posible.",
    "clases.faq.q6": "¿Por qué es una buena inversión?",
    "clases.faq.a6": "Por menos de 1,30 € al día, recibes un proyecto sorpresa exclusivo, inspiración, materiales y guía paso a paso. Es un momento para ti, para desconectar y desarrollar tu creatividad.",
    "clases.faq.q7": "¿Qué beneficios tiene tejer para mí?",
    "clases.faq.a7": "Tejer es mucho más que hacer manualidades: relaja y reduce el estrés, mejora la concentración, potencia tu creatividad, genera satisfacción y autoestima al ver un proyecto terminado hecho por ti, y te permite conectar con una comunidad creativa.",
    "clases.faq.q8": "¿Es tejer solo para invierno?",
    "clases.faq.a8": "¡Para nada! Cada proyecto está pensado para todo el año, incluyendo accesorios, decoración, regalos y proyectos prácticos que puedes usar en cualquier temporada.",

    "clases.final.title": "Empieza tu experiencia creativa",
    "clases.final.desc": "Si sientes que la creatividad forma parte de ti y quieres seguir explorándola, el Club Creativo MERAKI es tu lugar. Un espacio pensado para inspirarte, aprender y disfrutar de la creatividad cada mes.",
    "clases.final.btn": "✨ Únete hoy al Club Creativo y empieza a crear",
    "clases.final.quote": "“Invierte en ti misma: inspiración, manualidades y bienestar creativo cada mes.”",
    "clases.final.noCommitment": "Sin permanencia. Cancela cuando quieras."`,

  en: `    // Classes Landing (Clases.jsx)
    "clases.hero.title": "Create, learn, and enjoy every month.",
    "clases.hero.desc": "Every month you will discover creative projects, ideas, and inspiration to enjoy creativity at your own pace and dedicate a moment just to yourself.",
    "clases.hero.cta.unauth": "I want to join the club",
    "clases.hero.cta.authSub": "Go to my Academy →",
    "clases.hero.cta.subtext": "Start your creative moment today.",
    "clases.hero.loginText": "Already part of the club?",
    "clases.hero.loginLink": "Log in",

    "clases.whatIs.title": "What is the Creative Club?",
    "clases.whatIs.p1": "The MERAKI Creative Club is a space designed for people who enjoy creating with their hands, learning new things, and dedicating a moment to disconnect from the daily rhythm.",
    "clases.whatIs.p2": "By subscribing to the club, you will be part of a creative community where every month you will find exclusive projects, inspiring ideas, and craft proposals that will help you keep developing your creativity in a simple and enjoyable way.",
    "clases.whatIs.p3": "The goal of the Creative Club is to accompany you on your creative journey, offering inspiration, learning, and moments of calm through crafts. It doesn't matter if you are starting out or already have experience: the important thing is to have the desire to create and enjoy the process.",
    "clases.whatIs.quote": "More than just content, the Creative Club is a place to dedicate time to yourself, experiment with new techniques, and reconnect with the pleasure of creating.",

    "clases.benefits.title": "Benefits of belonging to the MERAKI Creative Club",
    "clases.benefits.subtitle": "If you like creating with your hands, now you can also do it from home with our MERAKI Creative Club",
    "clases.benefits.b1.title": "Exclusive projects every month",
    "clases.benefits.b1.desc": "Access creative proposals designed especially for club members, with new ideas to keep enjoying crafts.",
    "clases.benefits.b2.title": "Constant inspiration",
    "clases.benefits.b2.desc": "Discover new techniques, combinations, and proposals that will help you expand your knowledge and keep your creativity alive.",
    "clases.benefits.b3.title": "Clear and accessible explanations",
    "clases.benefits.b3.desc": "The projects are designed so you can easily carry them out, whether you are starting or already have experience.",
    "clases.benefits.b4.title": "Time for you",
    "clases.benefits.b4.desc": "Creativity is also a way to relax and disconnect. The club invites you to dedicate a moment of calm while creating with your hands.",
    "clases.benefits.b5.title": "Special benefits for members",
    "clases.benefits.b5.desc": "Club members will be able to enjoy special benefits related to certain Meraki ArteSano activities, workshops, or proposals.",
    "clases.benefits.b6.title": "Be part of a community",
    "clases.benefits.b6.desc": "A space to share a passion for crafts, learn together, and enjoy the creative process.",

    "clases.isForYou.title": "This club is for you if...",
    "clases.isForYou.subtitle": "The MERAKI Creative Club is designed for all people who feel that creating with their hands is a way to enjoy, relax, and express themselves.",
    "clases.isForYou.li1": "You like crafts and want to keep learning new ideas and techniques.",
    "clases.isForYou.li2": "You enjoy creating and would like to dedicate more time to your creativity.",
    "clases.isForYou.li3": "You are looking for an activity to help you relax and disconnect from everyday life.",
    "clases.isForYou.li4": "You love discovering new projects and letting your imagination fly.",
    "clases.isForYou.li5": "You want to be part of a creative space for inspiration.",
    "clases.isForYou.li6": "If you cannot attend in-person classes or prefer to create at your own pace, the MERAKI Creative Club is designed for you.",
    "clases.isForYou.bottomText": "It doesn't matter if you are starting or already have experience: the important thing is to have the desire to create and enjoy the process.",

    "clases.pricing.title": "What's included every month?",
    "clases.pricing.badge": "MERAKI Creative Club",
    "clases.pricing.inc1": "Complete kit with all materials.",
    "clases.pricing.inc1.sub": "It is very important to us that what you receive is from the best Spanish yarns.",
    "clases.pricing.inc2": "Clear, step-by-step printed instructions.",
    "clases.pricing.inc3": "Access to a 2h live session via Zoom or similar.",
    "clases.pricing.inc4": "Access to the recording.",
    "clases.pricing.inc5": "Private Telegram group.",
    "clases.pricing.inc6": "Exclusive project (aimed at both crochet and knitting).",
    "clases.pricing.inc7": "Among all that's included every month, there will be some surprise!",
    
    "clases.pricing.cal.title": "📅 Monthly Calendar",
    "clases.pricing.cal.li1": "From the 21st to 30th → Kit preparation.",
    "clases.pricing.cal.li2": "From the 1st to 5th → Box shipping.",
    "clases.pricing.cal.li3": "On the 15th → 2h Live session.",
    "clases.pricing.cal.li4": "From the 16th to 30th → Recording available.",
    
    "clases.pricing.diff.title": "🌟 Our Difference",
    "clases.pricing.diff.li1": "• Real guidance on every project.",
    "clases.pricing.diff.li2": "• We resolve your doubts step by step.",
    "clases.pricing.diff.li3": "• Be part of a community that enjoys creating.",
    "clases.pricing.diff.li4": "• Receive everything at home, ready to start.",
    "clases.pricing.diff.li5": "• Exclusive store benefits and future kits.",

    "clases.card.badge": "🚀 LAUNCH OFFER",
    "clases.card.title": "Monthly Subscription",
    "clases.card.officialPrice": "OFFICIAL PRICE 39€",
    "clases.card.price": "32",
    "clases.card.currency": "€/month",
    "clases.card.founderBadge": "🔥 FOUNDERS PRICE first month",
    "clases.card.limited": "Limited to {max} spots",
    "clases.card.spotsLeft": "only {left} left",
    "clases.card.soldOut": "🔒 Sold Out",
    "clases.card.quote": '💡 "A small price for great creative moments."',
    "clases.card.noCommitment": "No commitment • Cancel anytime",
    "clases.card.memberBtn": "✅ I'm a member — Go to my Academy",
    "clases.card.joinBtn": "I want to join the club",

    "clases.faq.title": "Frequently Asked Questions (FAQ)",
    "clases.faq.q1": "What experience level do I need?",
    "clases.faq.a1": "You don't need prior experience. Every surprise project comes with a step-by-step guide, photos, and tips, so you can enjoy creating from day one.",
    "clases.faq.q2": "What exactly does the kit include?",
    "clases.faq.a2": "Each month you will receive all the materials needed for the surprise project, plus the instruction guide. You only need your desire to create.",
    "clases.faq.q3": "Can I cancel the subscription at any time?",
    "clases.faq.a3": "Yes. The subscription is monthly and flexible; you can cancel it at any time before the next kit is shipped.",
    "clases.faq.q4": "What if I don't like the colors or materials?",
    "clases.faq.a4": "We select quality materials and matching colors for all tastes. Each kit is designed to be versatile and fun.",
    "clases.faq.q5": "When do I receive my surprise project?",
    "clases.faq.a5": "Kits are shipped at the beginning of each month (7th), so you can enjoy your surprise project as soon as possible.",
    "clases.faq.q6": "Why is it a good investment?",
    "clases.faq.a6": "For less than €1.30 a day, you receive an exclusive surprise project, inspiration, materials, and a step-by-step guide. It is a moment for yourself to disconnect and develop your creativity.",
    "clases.faq.q7": "What are the benefits of knitting for me?",
    "clases.faq.a7": "Knitting is much more than crafting: it relaxes and reduces stress, improves concentration, boosts your creativity, brings satisfaction and self-esteem seeing a finished project made by you, and allows you to connect with a creative community.",
    "clases.faq.q8": "Is knitting just for winter?",
    "clases.faq.a8": "Not at all! Every project is designed for year-round use, including accessories, decor, gifts, and practical projects you can use in any season.",

    "clases.final.title": "Start your creative experience",
    "clases.final.desc": "If you feel that creativity is part of you and want to keep exploring it, the MERAKI Creative Club is your place. A space designed to inspire, teach, and enjoy creativity every month.",
    "clases.final.btn": "✨ Join the Creative Club today and start creating",
    "clases.final.quote": "“Invest in yourself: inspiration, crafts, and creative well-being every month.”",
    "clases.final.noCommitment": "No commitment. Cancel anytime."`,

  fr: `    // Classes Landing (Clases.jsx)
    "clases.hero.title": "Créez, apprenez et profitez chaque mois.",
    "clases.hero.desc": "Chaque mois, vous découvrirez des projets créatifs, des idées et de l'inspiration pour profiter de la créativité à votre rythme et consacrer un moment rien qu'à vous.",
    "clases.hero.cta.unauth": "Je veux rejoindre le club",
    "clases.hero.cta.authSub": "Aller à mon Académie →",
    "clases.hero.cta.subtext": "Commencez votre moment créatif aujourd'hui.",
    "clases.hero.loginText": "Déjà membre du club ?",
    "clases.hero.loginLink": "Se connecter",

    "clases.whatIs.title": "Qu'est-ce que le Club Créatif ?",
    "clases.whatIs.p1": "Le Club Créatif MERAKI est un espace conçu pour les personnes qui aiment créer de leurs mains, apprendre de nouvelles choses et prendre un moment pour se déconnecter du rythme quotidien.",
    "clases.whatIs.p2": "En rejoignant le club, vous ferez partie d'une communauté créative où, chaque mois, vous trouverez des projets exclusifs, des idées inspirantes et des propositions artisanales pour vous aider à développer votre créativité de manière simple et agréable.",
    "clases.whatIs.p3": "L'objectif du Club Créatif est de vous accompagner dans votre parcours créatif en vous offrant inspiration, apprentissage et moments de calme grâce aux travaux manuels. Que vous débutiez ou ayez déjà de l'expérience : l'important est d'avoir envie de créer et d'apprécier le processus.",
    "clases.whatIs.quote": "Plus qu'un simple contenu, le Club Créatif est un lieu pour s'accorder du temps, expérimenter de nouvelles techniques et renouer avec le plaisir de créer.",

    "clases.benefits.title": "Avantages de faire partie du Club Créatif MERAKI",
    "clases.benefits.subtitle": "Si vous aimez créer de vos mains, vous pouvez désormais le faire depuis chez vous grâce à notre Club Créatif MERAKI",
    "clases.benefits.b1.title": "Des projets exclusifs chaque mois",
    "clases.benefits.b1.desc": "Accédez à des propositions créatives spécialement conçues pour les membres du club, avec de nouvelles idées pour continuer à profiter de l'artisanat.",
    "clases.benefits.b2.title": "Inspiration constante",
    "clases.benefits.b2.desc": "Découvrez de nouvelles techniques, combinaisons et propositions qui vous aideront à élargir vos connaissances.",
    "clases.benefits.b3.title": "Des explications claires et accessibles",
    "clases.benefits.b3.desc": "Les projets sont conçus pour que vous puissiez les réaliser facilement, que vous débutiez ou que vous ayez déjà de l'expérience.",
    "clases.benefits.b4.title": "Du temps pour vous",
    "clases.benefits.b4.desc": "La créativité est aussi une manière de se détendre. Le club vous invite à prendre un moment de calme tout en créant.",
    "clases.benefits.b5.title": "Avantages exclusifs pour les membres",
    "clases.benefits.b5.desc": "Les membres bénéficieront d'avantages liés à certaines activités, ateliers ou propositions de Meraki ArteSano.",
    "clases.benefits.b6.title": "Rejoignez une communauté",
    "clases.benefits.b6.desc": "Un espace pour partager sa passion pour l'artisanat, apprendre ensemble et profiter du processus créatif.",

    "clases.isForYou.title": "Ce club est pour vous si...",
    "clases.isForYou.subtitle": "Le Club Créatif MERAKI est conçu pour tous ceux qui sentent que créer est une façon de s'amuser, de se détendre et de s'exprimer.",
    "clases.isForYou.li1": "Vous aimez l'artisanat et voulez continuer à apprendre.",
    "clases.isForYou.li2": "Vous aimez créer et aimeriez y consacrer plus de temps.",
    "clases.isForYou.li3": "Vous cherchez une activité pour vous détendre et vous déconnecter.",
    "clases.isForYou.li4": "Vous aimez découvrir de nouveaux projets et laisser libre cours à votre imagination.",
    "clases.isForYou.li5": "Vous voulez faire partie d'un espace créatif inspirant.",
    "clases.isForYou.li6": "Si vous ne pouvez pas assister aux cours en présentiel, le Club Créatif MERAKI est fait pour vous.",
    "clases.isForYou.bottomText": "Que vous soyez débutant ou expérimenté, l'important est d'avoir envie de créer.",

    "clases.pricing.title": "Qu'est-ce qui est inclus chaque mois ?",
    "clases.pricing.badge": "Club Créatif MERAKI",
    "clases.pricing.inc1": "Kit complet avec tous les matériaux.",
    "clases.pricing.inc1.sub": "Il est très important pour nous que vous receviez les meilleures laines.",
    "clases.pricing.inc2": "Instructions imprimées étape par étape.",
    "clases.pricing.inc3": "Accès à une session en direct de 2h via Zoom.",
    "clases.pricing.inc4": "Accès à l'enregistrement.",
    "clases.pricing.inc5": "Groupe Telegram privé.",
    "clases.pricing.inc6": "Projet exclusif (tricot et crochet).",
    "clases.pricing.inc7": "En plus, il y aura quelques surprises !",
    
    "clases.pricing.cal.title": "📅 Calendrier Mensuel",
    "clases.pricing.cal.li1": "Du 21 au 30 → Préparation des kits.",
    "clases.pricing.cal.li2": "Du 1 au 5 → Expédition des boîtes.",
    "clases.pricing.cal.li3": "Le 15 → Session en direct de 2h.",
    "clases.pricing.cal.li4": "Du 16 au 30 → Enregistrement disponible.",
    
    "clases.pricing.diff.title": "🌟 Notre Différence",
    "clases.pricing.diff.li1": "• Accompagnement réel sur chaque projet.",
    "clases.pricing.diff.li2": "• Nous résolvons vos doutes étape par étape.",
    "clases.pricing.diff.li3": "• Faites partie d'une communauté qui aime créer.",
    "clases.pricing.diff.li4": "• Recevez tout chez vous, prêt à commencer.",
    "clases.pricing.diff.li5": "• Avantages exclusifs en boutique et sur les prochains kits.",

    "clases.card.badge": "🚀 OFFRE DE LANCEMENT",
    "clases.card.title": "Abonnement Mensuel",
    "clases.card.officialPrice": "PRIX OFFICIEL 39€",
    "clases.card.price": "32",
    "clases.card.currency": "€/mois",
    "clases.card.founderBadge": "🔥 PRIX FONDATEUR le premier mois",
    "clases.card.limited": "Limité à {max} places",
    "clases.card.spotsLeft": "il ne reste que {left}",
    "clases.card.soldOut": "🔒 Épuisé",
    "clases.card.quote": '💡 "Un petit prix pour de grands moments créatifs."',
    "clases.card.noCommitment": "Sans engagement • Annulez quand vous voulez",
    "clases.card.memberBtn": "✅ Je suis membre — Aller à mon Académie",
    "clases.card.joinBtn": "Je veux rejoindre le club",

    "clases.faq.title": "Foire Aux Questions (FAQ)",
    "clases.faq.q1": "Quel niveau d'expérience dois-je avoir ?",
    "clases.faq.a1": "Aucune expérience n'est requise. Chaque projet surprise comprend un guide étape par étape.",
    "clases.faq.q2": "Que comprend exactement le kit ?",
    "clases.faq.a2": "Chaque mois, vous recevrez tous les matériaux nécessaires avec le guide d'instructions.",
    "clases.faq.q3": "Puis-je annuler l'abonnement à tout moment ?",
    "clases.faq.a3": "Oui, l'abonnement est sans engagement et vous pouvez l'annuler à tout moment.",
    "clases.faq.q4": "Et si je n'aime pas les couleurs ?",
    "clases.faq.a4": "Nous sélectionnons des matériaux de qualité aux couleurs polyvalentes et appréciables.",
    "clases.faq.q5": "Quand recevrai-je mon projet ?",
    "clases.faq.a5": "Les kits sont expédiés début de mois (le 7).",
    "clases.faq.q6": "Pourquoi est-ce un bon investissement ?",
    "clases.faq.a6": "Pour moins de 1,30 € par jour, vous obtenez du matériel, de l'inspiration et du temps pour vous déconnecter.",
    "clases.faq.q7": "Quels sont les avantages du tricot ?",
    "clases.faq.a7": "Cela détend, améliore la concentration, stimule la créativité et génère de la satisfaction.",
    "clases.faq.q8": "Est-ce seulement pour l'hiver ?",
    "clases.faq.a8": "Pas du tout ! Il y a des projets pour toutes les saisons.",

    "clases.final.title": "Commencez votre expérience créative",
    "clases.final.desc": "Rejoignez le Club Créatif MERAKI. Un espace conçu pour vous inspirer et vous apprendre chaque mois.",
    "clases.final.btn": "✨ Rejoignez le Club Créatif aujourd'hui",
    "clases.final.quote": "“Investissez en vous : inspiration et bien-être créatif chaque mois.”",
    "clases.final.noCommitment": "Sans engagement. Annulez quand vous voulez."`,

  pt: `    // Classes Landing (Clases.jsx)
    "clases.hero.title": "Crie, aprenda e aproveite todo mês.",
    "clases.hero.desc": "A cada mês você descobrirá projetos criativos, ideias e inspiração para desfrutar da criatividade no seu ritmo e dedicar um momento só para você.",
    "clases.hero.cta.unauth": "Quero entrar no clube",
    "clases.hero.cta.authSub": "Ir para minha Academia →",
    "clases.hero.cta.subtext": "Comece seu momento criativo hoje.",
    "clases.hero.loginText": "Já faz parte do clube?",
    "clases.hero.loginLink": "Entrar",

    "clases.whatIs.title": "O que é o Clube Criativo?",
    "clases.whatIs.p1": "O Clube Criativo MERAKI é um espaço pensado para as pessoas que gostam de criar com as mãos, aprender coisas novas e dedicar um momento para desligar do ritmo do dia a dia.",
    "clases.whatIs.p2": "Ao se inscrever, você fará parte de uma comunidade criativa onde encontrará projetos exclusivos e inspirações para desenvolver sua criatividade de forma agradável.",
    "clases.whatIs.p3": "O objetivo é acompanhar você na sua jornada criativa. Não importa se você está começando ou já tem experiência, o importante é a vontade de criar.",
    "clases.whatIs.quote": "Mais que apenas conteúdo, o Clube Criativo é um lugar para dedicar tempo a você mesma e se reconectar com o prazer de criar.",

    "clases.benefits.title": "Benefícios de pertencer ao Clube Criativo",
    "clases.benefits.subtitle": "Se você gosta de artes manuais, agora pode fazer isso de casa",
    "clases.benefits.b1.title": "Projetos exclusivos mensais",
    "clases.benefits.b1.desc": "Acesse propostas criativas desenhadas especialmente para os membros.",
    "clases.benefits.b2.title": "Inspiração constante",
    "clases.benefits.b2.desc": "Descubra novas técnicas e propostas que manterão sua criatividade viva.",
    "clases.benefits.b3.title": "Explicações claras e fáceis",
    "clases.benefits.b3.desc": "Os projetos são feitos para você conseguir realizar de forma fácil.",
    "clases.benefits.b4.title": "Tempo para você",
    "clases.benefits.b4.desc": "A criatividade também é uma maneira de relaxar. Tire um momento só seu.",
    "clases.benefits.b5.title": "Vantagens especiais para membros",
    "clases.benefits.b5.desc": "Membros têm benefícios relacionados a oficinas e propostas exclusivas da loja.",
    "clases.benefits.b6.title": "Faça parte da comunidade",
    "clases.benefits.b6.desc": "Um espaço para compartilhar essa paixão por artes manuais e aprender juntas.",

    "clases.isForYou.title": "Este clube é para você se...",
    "clases.isForYou.subtitle": "Criatividade como forma de relaxar e expressar.",
    "clases.isForYou.li1": "Gosta de artesanato e quer continuar aprendendo.",
    "clases.isForYou.li2": "Gosta de criar e adoraria dedicar mais tempo para isso.",
    "clases.isForYou.li3": "Procura uma atividade relaxante para desconectar.",
    "clases.isForYou.li4": "Adora novos projetos para soltar a imaginação.",
    "clases.isForYou.li5": "Quer participar de um espaço criativo em conjunto.",
    "clases.isForYou.li6": "Prefere criar no seu ritmo e horário.",
    "clases.isForYou.bottomText": "Tanto para iniciantes quanto experiência.",

    "clases.pricing.title": "O que inclui a cada mês?",
    "clases.pricing.badge": "Clube Criativo MERAKI",
    "clases.pricing.inc1": "Kit completo com todos os materiais.",
    "clases.pricing.inc1.sub": "Enviamos apenas as melhores marcas.",
    "clases.pricing.inc2": "Instruções impressas com passo a passo.",
    "clases.pricing.inc3": "Acesso a 2h ao vivo pelo Zoom.",
    "clases.pricing.inc4": "Acesso vitalício à gravação.",
    "clases.pricing.inc5": "Grupo privado do Telegram.",
    "clases.pricing.inc6": "Projeto surpresa exclusivo.",
    "clases.pricing.inc7": "Para completar, sempre uma surpresa em cada caixa!",
    
    "clases.pricing.cal.title": "📅 Calendário Mensual",
    "clases.pricing.cal.li1": "Dia 21 a 30 → Preparação de kits.",
    "clases.pricing.cal.li2": "Dia 1 a 5 → Envio das caixas.",
    "clases.pricing.cal.li3": "Dia 15 → Aula ao vivo de 2h.",
    "clases.pricing.cal.li4": "Dia 16 a 30 → Gravação disponível.",
    
    "clases.pricing.diff.title": "🌟 Nossa Diferença",
    "clases.pricing.diff.li1": "• Acompanhamento real passo a passo.",
    "clases.pricing.diff.li2": "• Resolvemos todas suas dúvidas.",
    "clases.pricing.diff.li3": "• Comunidade amiga e criativa.",
    "clases.pricing.diff.li4": "• Receba tudo pronto sem sair de casa.",
    "clases.pricing.diff.li5": "• Vantagens super exclusivas na loja.",

    "clases.card.badge": "🚀 OFERTA DE LANÇAMENTO",
    "clases.card.title": "Assinatura Mensal",
    "clases.card.officialPrice": "PREÇO OFICIAL 39€",
    "clases.card.price": "32",
    "clases.card.currency": "€/mês",
    "clases.card.founderBadge": "🔥 PREÇO FUNDADORES apenas 1º mês",
    "clases.card.limited": "Limitado a {max} vagas",
    "clases.card.spotsLeft": "restam {left}",
    "clases.card.soldOut": "🔒 Esgotado",
    "clases.card.quote": '💡 "Um preço pequeno para grandes momentos."',
    "clases.card.noCommitment": "Sem fidelidade • Cancele quando quiser",
    "clases.card.memberBtn": "✅ Eu sou membro — Ir para minha Academia",
    "clases.card.joinBtn": "Quero entrar no clube",

    "clases.faq.title": "Perguntas Frequentes (FAQ)",
    "clases.faq.q1": "Qual nível de experiência preciso?",
    "clases.faq.a1": "Nenhum! Todos os projetos chegam com passo a passo.",
    "clases.faq.q2": "O que exatamente vem no kit?",
    "clases.faq.a2": "Os materiais necessários e surpresas mensais.",
    "clases.faq.q3": "Posso cancelar no mês seguinte?",
    "clases.faq.a3": "Sim, é livre de fidelidade.",
    "clases.faq.q4": "E se as cores não baterem?",
    "clases.faq.a4": "Sempre mandamos cores bonitas e materiais testados.",
    "clases.faq.q5": "Que dia chega na minha casa?",
    "clases.faq.a5": "Postamos sempre ao redor do inicio do mês.",
    "clases.faq.q6": "Por que vale a pena?",
    "clases.faq.a6": "É seu momento de relaxamento mensal com tudo incluso.",
    "clases.faq.q7": "Quais são os benefícios de criar manualidades?",
    "clases.faq.a7": "Redução do estresse e aumento da autoestima criativa.",
    "clases.faq.q8": "Lã é apenas no inverno?",
    "clases.faq.a8": "Também oferecemos projetos fáceis focados no verão e meia-estação quando a temperatura sobe.",

    "clases.final.title": "Comece sua experiência",
    "clases.final.desc": "Sinta o Clube Criativo e desfrute todo mês.",
    "clases.final.btn": "✨ Entre no Clube hoje mesmo",
    "clases.final.quote": "“Invista em você mesmo.”",
    "clases.final.noCommitment": "Sem Fidelidade."`
};

for (const lang of langs) {
  const filePath = path.join(dir, lang + '.js');
  let content = fs.readFileSync(filePath, 'utf8');

  // We split by "// Classes Landing (Clases.jsx)" and replace everything after it until "// Profile" starts
  const p1 = content.indexOf('// Classes Landing (Clases.jsx)');
  const p2 = content.indexOf('// Profile');
  
  if (p1 !== -1 && p2 !== -1) {
      const before = content.slice(0, p1);
      const after = content.slice(p2);
      fs.writeFileSync(filePath, before + newKeys[lang] + '\\n\\n    ' + after, 'utf8');
      console.log('Fixed:', lang);
  } else {
      console.error('Could not find split points in', lang);
  }
}
